### ISSUE TITLE
Port the strings from Java to JS

### ISSUE THREAD

**Issue by samreid** [phetsims/sugar-and-salt-solutions#1]

**Comment by samreid** [comment]
I need to port the strings from Java for Sugar and Salt Solutions. Should I run PropertiesToJSON then patch the broken JSON then use the script from https://github.com/phetsims/babel/issues/3 ?  I'm a bit out of the loop on this.  @pixelzoom and @jonathanolson I noticed you were working on babel#3, can you please advise here?

**Comment by pixelzoom** [comment]
The Java tools need to be modified to match the revised format of the HTML5 string files. See https://github.com/phetsims/chipper/issues/131

**Comment by ariel-phet** [comment]
@samreid wasn't this done as a batch? Can this be closed?

**Comment by samreid** [comment]
Yes, I see 36 translations converted from Java to babel/autoport, closing.
