### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sugar-and-salt-solutions#10]
Examples of anti pattern:

SugarAndSaltSharedProperties: sizeScale: new Property( 1.0 )
Dispenser: thisDispenser.enabled = new Property( false );
Dispenser:  thisDispenser.angle = new Property( angle );
Dispenser: thisDispenser.center = new Property( new Vector2( x, y ) );
SugarAndSaltSolutionMode: thisModel.dispenserType = new Property( DispenserType.SALT );

**Comment by veillette** [comment]
Closing this issue since it is a duplicate of #8
