### ISSUE TITLE
chem symbols should not be translatable 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sugar-and-salt-solutions#19]
See https://github.com/phetsims/molecules-and-light/issues/124.

**Comment by porygonj** [comment]
881098ba817b5b6a0112a10fb021f508bad896f3 We changed the calcium symbol's string to be hard-coded into the sim, rather than in the list of translatable strings.

**Comment by porygonj** [comment]
We moved the strings involving chemicals symbols to MicroSoluteKitList.js, from sugar-and-salt-solutions_en.json. I believe the all work for this issue is done. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good. I added a comment that refers to this issue, so that readers aren't wondering why these string are not translated.  

Closing.
