### ISSUE TITLE
Can we avoid using translatable strings in HTMLText?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sugar-and-salt-solutions#24]
See https://github.com/phetsims/special-ops/issues/18. If using them is a requirement, then let me know (I'll need to look into sanitization of translated strings).

**Comment by veillette** [comment]
I was able to find an old commit that addressed  0b71e9f5e23799db286c87da46ef7d2813694739 this issue.
There are no longer any instances of HTMLText in this simulation.
