### ISSUE TITLE
Code should be auto-formatted

### ISSUE THREAD

**Issue by samreid** [phetsims/sugar-and-salt-solutions#6]
When applying the https://github.com/phetsims/joist/blob/master/util/phet-idea-codestyle.xml code style formatting, I see 12 modified files.  The files should be formatted using IDEA's autoformatter to standardize formatting, simplify diffs and reviews by other PhET team members.

I normally leave IDEA's "reformat before committing" checkbox checked, though I sometimes have to remember to uncheck that when working with 3rd party code that isn't formatted with our auto-formatter.

**Comment by veillette** [comment]
The code is currently following the codestyle. 
However, it is good to have the codestyle to be applied by default before making a commit.

This can be done by ticking the appropriate box in webstorm.  
![image](https://user-images.githubusercontent.com/7633344/37658026-e59e6330-2c22-11e8-8ab8-37b00e2ca9cf.png)

Assigning to @smrtalec95 to make sure that your box is appropriately checked.
Once this is done you can close the issue.

**Comment by smrtalec95** [comment]
I have checked that box in my IDE.
