### ISSUE TITLE
error when using Evaporation slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sugar-and-salt-solutions#9]
I noticed this while testing a refactor in https://github.com/phetsims/scenery-phet/issues/140, it occurs in master on all platforms.

To reproduce:
1. start sim
2. go to 'Micro' screen
3. shake out some sodium (so that molecules are visible)
4. move the Evaporation slider, the sim will throw an error

Here's the console output:

![screenshot_479](https://cloud.githubusercontent.com/assets/3046552/6534694/a0178026-c3fc-11e4-8362-75a3c8f4eb09.png)

**Comment by veillette** [comment]
This issue is stale as one is no longer able to reproduce this error. Closing.
